apiVersion: v1
kind: Secret
metadata:
  name: properties-secret
  namespace: agrosolutions-properties
type: Opaque
stringData:
  JWT_ISSUER: "#{JwtIssuer}#"
  JWT_AUDIENCE: "#{JwtAudience}#"
  JWT_KEY: "#{JwtKey}#"
  PROPERTIES_CONNECTION_STRING: "#{PropertiesConnectionString}#"